### ISSUE TITLE
Not working in xcode 7.x + 

### ISSUE THREAD

**Issue by Pyrolr** [calimarkus/JDPluginManager#19]
I have tried adding plugin via Alcatraz in xcode 7,7.1,7.2 but in none of the xcode plugin menu is visible 
Any one is able to have plugin menu in xcode 7.x + ? 
Is there any setting needs to be enable ? I have restarted xcode multiple times

**Comment by Pyrolr** [comment]
Solved by adding DVTPlugInCompatibilityUUIDs xcode

**Comment by jaydee3** [comment]
Can you send a PR for that?
